  project:
    type: website

  website:
    page-navigation: true
    title: "CA SWAMP Bioaccumulation Monitoring Program and Safe to Eat Workgroup Frequently Asked Questions"
    site-url: "https://cawaterboarddatacenter.github.io/stew-faq/"
    repo-url: https://github.com/CAWaterBoardDataCenter/stew-faq
    repo-actions: [edit, source, issue]
    favicon: images/logos.png
  
    page-footer:
      right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
      left: "&copy; CC-By CA Water Board, 2024"
    
    sidebar:
      logo: "images/logos.png"
      favicon: images/logos.png
      pinned: true
      align: center
      tools: 
        - icon: globe
          href: https://mywaterquality.ca.gov/monitoring_council/bioaccumulation_oversight_group/index.html
          text: "STEW Webpage"
        - icon: github
          href: https://github.com/CAWaterBoardDataCenter/stew-faq
          text: "STEW FAQ"
  
      style: "docked"
      search: true
      collapse-level: 1
      contents:
        - href: index.qmd
          text: Welcome!
        - href: network.qmd
          text: Who are our partners?
        - href: data-use-wq.qmd
          text: How is our data used to protect and restore water quality?
        - href: data-use-human.qmd
          text: How is our data used to protect human health?
        - section: other-faq/index.qmd
          text: Other FAQs
          contents:
            - swamp-stew.qmd
            - advise.qmd
            - science.qmd
            - data-use-faq.qmd
            - regs.qmd
        - href: contribute.qmd
          text: Contributing

  format:
    html:
      theme: cosmo
      code-copy: true
      code-overflow: wrap
      toc: true
      fontsize: 1em


  filters:
    - include-files.lua
    - quarto

  execute:
    freeze: auto