project:
  type: website

book:
  title: "CA SWAMP Bioaccumulation Monitoring Program and Safe to Eat Workgroup Frequently Asked Questions"
  author: "CA Surface Water Ambient Monitoring Program (SWAMP)"
  date: "2024-01-01"
  search: true
  repo-url: https://github.com/CAWaterBoardDataCenter/stew-faq
  repo-actions: [edit, issue]
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  chapters:
  
    - index.qmd
    - network.qmd
    - data-use-wq.qmd
    - data-use-human.qmd
    - data-use-faq.qmd
    - science.qmd
    - advise.qmd
    - swamp-stew.qmd
    - regs.qmd
    - contribute.qmd
   
    
  sidebar:
    style: "docked"
    logo: "images/logos.png"
    # type: "light"
    # background: "#002151"
    # foreground: "light"
    border: true

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

# comments:
#   hypothesis: true