# **Welcome to the STEW FAQ!**

Here you will find answers to frequently asked questions (FAQs) related to the [SWAMP Bioaccumulation Monitoring Program](https://www.waterboards.ca.gov/water_issues/programs/swamp/bioaccumulation_monitoring.html) (Program), the [Safe to Eat Workgroup](https://mywaterquality.ca.gov/monitoring_council/bioaccumulation_oversight_group/) (STEW), and related bioaccumulation topics.

FAQs within this resource include:

-   [Who are our partners?](https://cawaterboarddatacenter.github.io/stew-faq/network.html)
-   [How are bioaccumulation data used to protect and restore water quality in CA?](https://cawaterboarddatacenter.github.io/stew-faq/data-use-wq.html)
-   [How are bioaccumulation data used to protect human health in CA?](https://cawaterboarddatacenter.github.io/stew-faq/data-use-human.html)
-   FAQs related to other topics, including:
    -   [The SWAMP Bioaccumulation Monitoring Program and STEW](https://cawaterboarddatacenter.github.io/stew-faq/swamp-stew.html)

    -   [Consumption Risks & Advise](https://cawaterboarddatacenter.github.io/stew-faq/advise.html)

    -   [Harmful Chemicals](Harmful Chemicals FAQs)

    -   [Bioaccumulation Science & Monitoring](Bioaccumulation science & monitoring FAQs)

    -   [Bioaccumulation Data Life Cycle](https://cawaterboarddatacenter.github.io/stew-faq/data-cycle.html)

    -   [Laws & Regulations](https://cawaterboarddatacenter.github.io/stew-faq/regs.html)

This [Quarto book](https://quarto.org/docs/books) is an open, living, and continuously iterating resource. If you have suggestions for additions or revisions you think should be incorporated into this resource, please follow the guidance provided in the [Contributing](https://cawaterboarddatacenter.github.io/stew-faq/contribute.html) section.
